version: "3.9"
services:
  web:
    build: .
    # Start with hot reloading
    command: /bin/sh -c "/start-reload.sh"
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://postgres:docker@database:5432/analysisdb
    depends_on:
      - database
  database:
    image: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=analysisdb

volumes:
  postgres_data:
