"""Remove constraints from EventBase

Revision ID: a9e0824de944
Revises: e359e36e10ce
Create Date: 2021-10-11 15:55:10.650746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9e0824de944'
down_revision = 'e359e36e10ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventsuggestion', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('eventsuggestion', 'status',
               existing_type=postgresql.ENUM('published', 'draft', 'deleted', name='eventstatus'),
               nullable=True)
    op.drop_index('ix_eventsuggestion_ends_at', table_name='eventsuggestion')
    op.drop_index('ix_eventsuggestion_starts_at', table_name='eventsuggestion')
    op.drop_index('ix_eventsuggestion_url', table_name='eventsuggestion')
    op.alter_column('eventversion', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('eventversion', 'status',
               existing_type=postgresql.ENUM('published', 'draft', 'deleted', name='eventstatus'),
               nullable=True)
    op.drop_index('ix_eventversion_ends_at', table_name='eventversion')
    op.drop_index('ix_eventversion_starts_at', table_name='eventversion')
    op.drop_index('ix_eventversion_url', table_name='eventversion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_eventversion_url', 'eventversion', ['url'], unique=False)
    op.create_index('ix_eventversion_starts_at', 'eventversion', ['starts_at'], unique=False)
    op.create_index('ix_eventversion_ends_at', 'eventversion', ['ends_at'], unique=False)
    op.alter_column('eventversion', 'status',
               existing_type=postgresql.ENUM('published', 'draft', 'deleted', name='eventstatus'),
               nullable=False)
    op.alter_column('eventversion', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_eventsuggestion_url', 'eventsuggestion', ['url'], unique=False)
    op.create_index('ix_eventsuggestion_starts_at', 'eventsuggestion', ['starts_at'], unique=False)
    op.create_index('ix_eventsuggestion_ends_at', 'eventsuggestion', ['ends_at'], unique=False)
    op.alter_column('eventsuggestion', 'status',
               existing_type=postgresql.ENUM('published', 'draft', 'deleted', name='eventstatus'),
               nullable=False)
    op.alter_column('eventsuggestion', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
